version: "3.9"
services:
  app:
    build: .
    image: unified_shodan_api
    container_name: unified_shodan_api_container
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./json:/app/json
      - ./reportes_dns:/app/reportes_dns
    command: python main.py
